project:
  title: "AI for Actuaries"
  type: website
  render:
    - "*.qmd"
    - "!*.ipynb"
    - "!*.md"
  output-dir: docs

website:
  title: "AI for Actuaries"
  page-navigation: true
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - section: "Module 1"
        contents:
          - Lecture-1-Artificial-Intelligence/course-overview.qmd
          # - MX-Neural-Networks/neural-networks.qmd
          # - Lecture-1-Artificial-Intelligence/artificial-intelligence.qmd
          - Lecture-1-Artificial-Intelligence/python.qmd
      - section: "Module 2"
        contents:
          - Lecture-2-Deep-Learning-Keras/deep-learning-keras.qmd
          - Lecture-2-Deep-Learning-Keras/project.qmd
      - section: "Module 3"
        contents:
          - Lecture-3-Tabular-Data/categorical-variables.qmd
          - Lecture-3-Tabular-Data/classification.qmd
      - section: "Module 4"
        contents:
          - Lecture-4-Computer-Vision/computer-vision.qmd
      - section: "Module 5"
        contents:
          - Lecture-5-Natural-Language-Processing/natural-language-processing.qmd
      - section: "Module 6"
        contents:
          - Lecture-6-Uncertainty-Quantification/uncertainty-quantification.qmd
      - section: "Module 7"
        contents:
          - Lecture-7-Recurrent-Neural-Networks-And-Time-Series/rnns-and-time-series.qmd
      - section: "Module 8"
        contents:
          - Lecture-8-Generative-Networks/generative-networks.qmd
          - Lecture-8-Generative-Networks/gans.qmd
      - section: "Module 9"
        contents:
          - Lecture-9-Advanced-Topics/interpretability.qmd
          - Lecture-9-Advanced-Topics/exam-revision.qmd
      

format:
  html:
    theme: "serif"
    css: styles.css
    toc: true

  revealjs:
    output-ext: "slides.html"
    theme: [serif, custom.scss]
    controls: true
    controls-tutorial: true
    logo: unsw-logo.png
    transition: none
    slide-number: c/t
    preview-links: false
    margin: 0.12
    width: 1000
    chalkboard:
      boardmarker-width: 4
      grid: false
      background:
        - "rgba(255,255,255,0.0)"
        - "https://github.com/rajgoel/reveal.js-plugins/raw/master/chalkboard/img/blackboard.png"
    history: false
    code-annotations: none

subtitle: ACTL3143 & ACTL5111 Deep Learning for Actuaries
author: Patrick Laub
strip-comments: true
html-math-method: katex
jupyter: ai
execute:
  echo: true
  freeze: true
  daemon: false