project:
  title: "AI for Actuaries"
  type: website
  render:
    - "*.qmd"
    - "!*.ipynb"
    - "!*.md"
  output-dir: docs
  post-render:
    - scripts/decktape-pdfs.py

website:
  title: "AI for Actuaries"
  page-navigation: true
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - section: "Module 1"
        contents:
          - Lecture-1-Artificial-Intelligence/course-overview.qmd
          - Lecture-1-Artificial-Intelligence/artificial-intelligence.qmd
          - Lecture-1-Artificial-Intelligence/python.qmd
          - Labs/python-lab.qmd
          - Labs/python-for-data-science-lab.qmd
          - Exercises/chess-ai.qmd
      - section: "Module 2"
        contents:
          - Lecture-2-Deep-Learning-Keras/project.qmd
          - Lecture-2-Deep-Learning-Keras/deep-learning-keras.qmd
          - Lecture-3-Tabular-Data/categorical-variables.qmd
          - Lecture-3-Tabular-Data/classification.qmd
          - Labs/forward-pass-lab.qmd
          - Labs/matplotlib-lab.qmd
          - Exercises/victorian-crash-severity.qmd
      - section: "Module 3"
        contents:
          - Lecture-4-Computer-Vision/computer-vision.qmd
          - Labs/optimisation-lab.qmd
          - Labs/latex-lab.qmd
          - Exercises/hurricane-damage.qmd
      - section: "Module 4"
        contents:
          - Lecture-5-Natural-Language-Processing/natural-language-processing.qmd
          - Exercises/police-reports.qmd
      - section: "Module 5"
        contents:
          - Lecture-7-Recurrent-Neural-Networks-And-Time-Series/rnns-and-time-series.qmd
          - Exercises/sydney-airport-temperature.qmd
      - section: "Module 6"
        contents:
          - Lecture-6-Distributional-Regression/optimisation.qmd
          - Lecture-6-Distributional-Regression/distributional-regression.qmd
          - Labs/backpropagation-lab.qmd
          - Labs/distributional-regression-lab.qmd
      - section: "Module 7"
        contents:
          - Lecture-9-Advanced-Topics/interpretability.qmd
      - section: "Module 8"
        contents:
          - Lecture-8-Generative-Networks/generative-networks.qmd
          - Lecture-8-Generative-Networks/gans.qmd
      - section: "Module 9"
        contents:
          - Lecture-9-Advanced-Topics/next-steps.qmd

format:
  html:
    theme: [serif, shared.scss, html-style.scss]
    toc: true
    shift-heading-level-by: 1

  revealjs:
    output-ext: "slides.html"
    theme: [serif, shared.scss, revealjs-style.scss]
    controls: true
    controls-tutorial: true
    logo: unsw-logo.png
    transition: none
    slide-number: c/t
    preview-links: false
    margin: 0.10
    width: 1000
    chalkboard:
      boardmarker-width: 4
      grid: false
      background:
        - "rgba(255,255,255,0.0)"
        - "https://github.com/rajgoel/reveal.js-plugins/raw/master/chalkboard/img/blackboard.png"
    history: false
    code-annotations: none
    filters:
      - reveal-auto-agenda
    auto-agenda:
      heading: Lecture Outline

subtitle: ACTL3143 & ACTL5111 Deep Learning for Actuaries
author: Patrick Laub
strip-comments: true
html-math-method: katex
highlight-style: blue-pygments.theme
syntax-definitions:
  - python.xml
pdf-engine: pdflatex
execute:
  echo: true
  freeze: false
  daemon: false